### PR TITLE
Handle nested interpolations

### PR DESCRIPTION
**Pull request by arielkru**
Nested interpolations are raising errors.
The fix lets interpolations contain other interpolations inside them, like this example:

```
resource "example" "example" {
tags = "${merge(var.common_tags, map( "name", "dependency", "${var.input_dependency_value}"))}"
}
```

### CODE REVIEW

**Review by aoskotsky-amplify — COMMENTED** [review]
Nice. Thanks for the PR!

Could you update the unit tests to add an example that covers this case?

**Comment by matt-land** [comment]
I will add unit tests, this is an issue I was facing and unable to solve.

**Comment by matt-land** [comment]
I created the tests, and PR'ed against the repo that opened the PR. 
However, one of the test cases isn't working. I believe the test is correct, and that the parser is not able to process the string interpolation correctly, even with the new functionality.

https://github.com/arielkru/python-hcl2/pull/1

The test cases I added are representative of actual TF string interpolations I am encountering/using.  I was unable to extend the Lark functionality to handle them.

**Comment by aoskotsky-amplify** [comment]
@matt-land Hey which test case isn't working for you? All of your test cases seem fine to me

**Comment by aoskotsky-amplify** [comment]
@matt-land I had to update the tests https://github.com/amplify-education/python-hcl2/pull/61/commits/7020ee07a9fc9713a6442135294bebf9c44b8cd1 to include the fixed list handling that was added in 3.0.0 but otherwise the tests look fine to me. Let me know which one was failing for you

**Review by jconstance-amplify — APPROVED** [review]

**Pull request merged**
