### PR TITLE
`lark>=0.11` support restore

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by rddimon** [comment]
In my opinion, it's not needed

@aoskotsky-amplify @htorianik What do you guys think?

**Comment by aoskotsky-amplify** [comment]
> In my opinion, it's not needed
> 
> @aoskotsky-amplify @htorianik What do you guys think?

Yea not sure if this is needed since we control the version of lark we are using with the requirements.txt file

**Comment by KOLANICH** [comment]
>since **we** control the version of lark we are using

IMHO it's up to **users** to control versions of the libs **they** have on their machines. Libs and software should be compatible to wide range of deps and dropping some versions just for dictating a user (and also to other software developes) what he must use specific versions without a strong real need to do so is IMHO the way to dependency hell.

Dependency pinning, and such "solutions" to dependency hell as self-sufficient containers, virtual environments and vendorization of deps are considered cancer killing the software ecosystem.

My PR for support lark>=1 was mainly motivated by the thing that it's me who controls the versions of software. So I usually use bleeding edge versions of packages, not the ones prescribed by someone. Without virtual environments. All the packages are installed globally. And usually it works. Sometimes it breaks and I fix it.

But me using bleeding edge versions of software shouldn't be confused with desire to drop old versions. Dropping a version is usurping some control from a user, and one needs really strong reasons to do it.

**Comment by rddimon** [comment]
@KOLANICH thank you for your work. We appreciate your contribution! 

As I can see, in version 1.0.0 and above the support of python 2.x is dropped for the `lark` package https://pypi.org/project/lark/1.0.0/
And it's a strong reason for dropping older versions in our package too
At the same time, we are adding complexity to the code which is hard to maintain

Overall, I don't see a benefit of this change just more complex and harder to maintain code

**Comment by KOLANICH** [comment]
>support of python 2.x is dropped

This PR is not about python 2.

>At the same time, we are adding complexity to the code which is hard to maintain

Every feature is complexity. It is a quality/complexity tradeoff. I don't consider 33 lines of code (including whitespaces by `black`) as too high price for supporting more versions (and I guess even more can be supported with few more lines of code, basically I just got an import error for the features that are not needed by users installing from a pypi wheel (standalone parser generation, in wheels it should be pregenerated, but tests deleted the pregenerated parser, so they didn't pass for `0.11`, but I prefer to deal with complex problems step by step)).

**Comment by KOLANICH** [comment]
*`0.10`

**Comment by KOLANICH** [comment]
1. It turns out that the standalone parser generated by the latest lark is compatible to `lark 0.6` runtime
2. I have fixed the tests.
    a. when lark is `<0.11`, standalone parser generation is disabled in tests.
    b. added patching the expected JSON output to the one expected from `lark<1` when needed. It is not about generated standalone parser, but about our walker and lark runtime used by it. It can be that either the code for `0.` was wrong, or that my port for `1` was a wrong and that the test JSON file shouln;t have been changed. I want you to check that moment.

**Comment by rddimon** [comment]
With those changes, we are adding more complexity to the package:

1. We are adding support for the 2 major versions here `0.x` and `1.x`, which we wild like to avoid
2. With future features we will need to support 2 major versions, which will involve more work and complexity. We would like to avoid it
3. Currently, we support only `1.x` version check in PRs, which is not well right now. With the new changes, we will need to develop 2 types of testing for the `0.x` version and the `0.1` version, which we would like to avoid
4. By setting lark version >= 1 we are forcing people to use Python 3.6 and above. As python 2.7 EOF is 01 Jan 2020
5. With these changes we are extending vulnerability which we would like to avoid

We appreciate your work but there are more cons than pros with those changes.


If other folks have another opinion please live comments here

**Comment by KOLANICH** [comment]
>`we are forcing people`

It is not a decent goal.

**Comment by rddimon** [comment]
> > `we are forcing people`
> 
> It is not a decent goal.

It's our internal goal as that package is used primarily for our internal needs

**Comment by rddimon** [comment]
Closing and we don't plan to support it

**Pull request closed without merging**
